server:
  port: 8888
  max-http-header-size: 10000000
 
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nuwan-git/microservices-course-on-youtube-config-store
          search-paths:
           - 'service-config/*service'

